export const APP_LAUNCH_SCENE = 'APP_LAUNCH_SCENE';
export const APP_SCENE = 'APP_SCENE';
export const PRACTICE_SCENE = 'PRACTICE_SCENE';
export const SIGNUP_SCENE = 'SIGNUP_SCENE';
export const COUNTRIES_LIST_SCENE = 'COUNTRY_LIST_SCENE';
